
BEGIN
   -- 1. ลบกลุ่ม Trading Engine 
   EXECUTE IMMEDIATE 'DROP TABLE Trades CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Buy_Orders CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Sell_Orders CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Tick_Data CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Market_Tickers CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Trading_Pairs CASCADE CONSTRAINTS';

   -- 2. ลบกลุ่ม Asset & Accounting
   EXECUTE IMMEDIATE 'DROP TABLE Fiat_Transactions CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Holdings CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Portfolio CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Accounts CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Assets CASCADE CONSTRAINTS';

   -- 3. ลบกลุ่ม User Cluster 
   EXECUTE IMMEDIATE 'DROP TABLE Bank_Accounts CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KYC_Documents CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE KYC_Verification CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE API_Keys CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Login_History CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE User_Address CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';

EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

SELECT table_name FROM user_tables;
